# 床群bot配置文件

#################################################
# authkey: mirai-http-api设置的authKey
authkey: INITKEY111111

# port: mirai-http-api设置的监听端口，请求将发送至http://localhost:port
port: 23456

# use_ws: 使用websocket获取事件、消息等
use_ws: true

# log_level: 日志等级  0:ERROR / 1:WARN / 2:INFO / 3:DEBUG
log_level: 2

# qq: 机器人qq号，必须是mirai已登录的账号
qq: 1234567890

#################################################
# qq_root: 管理员qq号
qq_root: 9876543210

# api_port: 床群bot的API监听端口，注意不要和port混淆
api_port: 0
